language: rust
cache: cargo

env:
  global:
    - CLIPPY_VERSION=0.0.212

rust:
  - stable
  - nightly-2019-02-26

before_script:
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "nightly-2019-02-26" ]]; then
      cargo install clippy --vers $CLIPPY_VERSION --force;
    fi'

script:
  - cargo build
  - cargo test
  - cargo doc --no-deps
  - cargo build --all-features
  - cargo test --all-features
  - cargo doc --all-features --no-deps
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "nightly-2019-02-26 ]]; then cargo clippy -- -D warnings --all; fi'
