language: rust
cache: cargo

rust:
  - stable
  - nightly-2019-02-26

before_script:
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "nightly-2019-02-26" ]]; then
      cargo install clippy --force;
    fi'

script:
  - cargo build
  - cargo test
  - cargo doc --no-deps
  - cargo build --all-features
  - cargo test --all-features
  - cargo doc --all-features --no-deps
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "nightly-2019-02-26" ]]; then cargo clippy --all -- -D warnings; fi'
